---
- name: Ensure .ssh directory exists for ubuntu user
  file:
    path: /home/ubuntu/.ssh
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0700"

- name: Add public key to ubuntu user's authorized_keys
  authorized_key:
    user: ubuntu
    key: "{{ lookup('file', '~/.ssh/ansible-key.pub') }}"
    state: present
